version: '3.8'

services:
  frontend:
    build:
      context: ./chinese-chess-frontend  # 指向前端代码的目录
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://localhost:8080  # 后端API的URL
      VITE_WEBSOCKET_URL: ws://localhost:8080/ws  # WebSocket的URL
    depends_on:
      - backend

  backend:
    build:
      context: ./chinese-chess-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      FRONTEND_URL: http://localhost
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_NAME: chinese_chess
      DB_PORT: 3306
      DB_LOG_LEVEL: silent
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GO_ENV: docker
      # REDIS_PASSWORD: 
      
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: chinese_chess
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

volumes:
  mysql-data: